FROM node:20-alpine

RUN mkdir -p /var/www/central-user-panel/nuxt-app-dev
WORKDIR /var/www/central-user-panel/nuxt-app-dev

COPY package*.json ./
RUN yarn install

COPY . .

EXPOSE 3000

CMD [ "yarn", "dev" ]
