version: "3.7"

services:
  nuxt-app:
    build:
      context: .
      dockerfile: ../Dockerfile.production
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "3000:3000"
    command: "node .output/server/index.mjs"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
